services:
  kong-migrations:
    image: kong:3.9.1
    container_name: kong-migrations
    environment:
      KONG_DATABASE: ${KONG_DATABASE:-postgres}
      KONG_PG_HOST: ${KONG_PG_HOST}
      KONG_PG_USER: ${KONG_PG_USER}
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD}
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_SSL: ${KONG_PG_SSL:-on}
      KONG_PG_SSL_VERIFY: ${KONG_PG_SSL_VERIFY:-off}
    command: kong migrations bootstrap
    restart: "no"
    networks:
      - kong-net

  kong:
    image: kong:3.9.1
    user: "root"
    container_name: kong
    depends_on:
      - kong-migrations
    restart: unless-stopped
    environment:
      KONG_DATABASE: ${KONG_DATABASE}
      KONG_PG_HOST: ${KONG_PG_HOST}
      KONG_PG_USER: ${KONG_PG_USER}
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD}
      KONG_PG_DATABASE: ${KONG_PG_DATABASE}
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:${KONG_ADMIN_PORT}
      KONG_PG_SSL: ${KONG_PG_SSL}
      KONG_PG_SSL_VERIFY: ${KONG_PG_SSL_VERIFY}
    volumes:
      - /opt/kong/logs:/usr/local/kong/logs
      - /opt/kong/pids:/usr/local/kong/pids
      - /opt/kong/sockets:/usr/local/kong/sockets
    ports:
      - "${KONG_PROXY_PORT}:8000"
      - "${KONG_PROXY_SSL_PORT}:8443"
      - "${KONG_ADMIN_PORT}:8001"
      - "${KONG_ADMIN_SSL_PORT}:8444"
    networks:
      - kong-net

  konga-db:
    image: mysql:5.7
    container_name: konga-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${KONGA_RP_PASSWORD}
      MYSQL_DATABASE: ${KONGA_PG_DATABASE}
      MYSQL_USER: ${KONGA_PG_USER}
      MYSQL_PASSWORD: ${KONGA_PG_PASSWORD}
    volumes:
      - /opt/konga/mysql:/var/lib/mysql
    networks:
      - kong-net

  konga-proxy:
    image: nginx:1.29.3
    container_name: konga-proxy
    restart: unless-stopped
    depends_on:
      - konga
    volumes:
      - ./config/nginx-konga.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3366:80"
    networks:
      - kong-net

  konga:
    image: pantsel/konga:0.14.9
    container_name: konga
    restart: unless-stopped
    depends_on:
      - konga-db
      - kong
    environment:
      DB_ADAPTER: mysql
      DB_HOST: konga-db
      DB_USER: ${KONGA_PG_USER}
      DB_PASSWORD: ${KONGA_PG_PASSWORD}
      DB_DATABASE: ${KONGA_PG_DATABASE}
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge
